### ISSUE TITLE
Add Image

### ISSUE THREAD

**Issue by rwieruch** [the-road-to-learn-react/react-router-dynamic-routes-example#1]
![react-router-example](https://user-images.githubusercontent.com/2479967/31482949-a9e6465a-af54-11e7-9c37-10a6746b9500.gif)

**Comment by simon-shuffle** [comment]
hello world

**Comment by ma-nish** [comment]
This is a testing comment addition through gql.

**Comment by ugursinans** [comment]
This is a second testing comment addition through gql .
